//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strokes.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AchivementResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AchivementResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Strokes.Core.Properties.AchivementResources", typeof(AchivementResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Length property of an array.
        /// </summary>
        public static string ArrayLengthPropertyAchievementDescription {
            get {
                return ResourceManager.GetString("ArrayLengthPropertyAchievementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array length.
        /// </summary>
        public static string ArrayLengthPropertyAchievementName {
            get {
                return ResourceManager.GetString("ArrayLengthPropertyAchievementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a Caesar encryption/decryption module.
        /// </summary>
        public static string CaesarChallengeDescription {
            get {
                return ResourceManager.GetString("CaesarChallengeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caesar.
        /// </summary>
        public static string CaesarChallengeName {
            get {
                return ResourceManager.GetString("CaesarChallengeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implement the ICalculator interface.
        /// </summary>
        public static string CalculatorChallengeDescription {
            get {
                return ResourceManager.GetString("CalculatorChallengeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        public static string CalculatorChallengeName {
            get {
                return ResourceManager.GetString("CalculatorChallengeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare an array.
        /// </summary>
        public static string DeclareArrayAchievementDescription {
            get {
                return ResourceManager.GetString("DeclareArrayAchievementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare an array.
        /// </summary>
        public static string DeclareArrayAchievementName {
            get {
                return ResourceManager.GetString("DeclareArrayAchievementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare and initialize an array with an initializer list.
        /// </summary>
        public static string DeclareInitArrayAchievementDescription {
            get {
                return ResourceManager.GetString("DeclareInitArrayAchievementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare and initialize an array with an initializer list.
        /// </summary>
        public static string DeclareInitArrayAchievementName {
            get {
                return ResourceManager.GetString("DeclareInitArrayAchievementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare a multidimensional array.
        /// </summary>
        public static string DeclareMultipleDimArrayAchievementDescription {
            get {
                return ResourceManager.GetString("DeclareMultipleDimArrayAchievementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare a multidimensional array.
        /// </summary>
        public static string DeclareMultipleDimArrayAchievementName {
            get {
                return ResourceManager.GetString("DeclareMultipleDimArrayAchievementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare a jagged multidimensional array ([][] instead of [,]).
        /// </summary>
        public static string JaggedArrayAchievementDescription {
            get {
                return ResourceManager.GetString("JaggedArrayAchievementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JAG.
        /// </summary>
        public static string JaggedArrayAchievementName {
            get {
                return ResourceManager.GetString("JaggedArrayAchievementName", resourceCulture);
            }
        }
    }
}
